name: ci
on:
  push:
    branches: [main]
  pull_request:
jobs:
  web:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: web
    steps:
      - uses: actions/checkout@v4
      - uses: oven-sh/setup-bun@v2
        with:
          bun-version: latest
      - run: bun install --frozen-lockfile
      - run: bunx turbo run check-types -F web
        env:
          NODE_ENV: development
          VITE_SERVER_URL: http://localhost:3000
